# Generated by Django 5.2.10 on 2026-01-15 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Kategori',
            },
        ),
        migrations.CreateModel(
            name='Destinasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_destinasi', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('deskripsi', models.TextField()),
                ('kecamatan', models.CharField(max_length=100)),
                ('lokasi_maps', models.CharField(max_length=300)),
                ('foto_utama', models.ImageField(upload_to='destinations/primary/')),
                ('foto_lainnya', models.ImageField(blank=True, null=True, upload_to='destinations/secondary/')),
                ('jumlah_views', models.IntegerField(default=0)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('pengelola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinasi_dikelola', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Destinasi',
            },
        ),
    ]
