# Generated by Django 5.1.3 on 2026-01-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_destinasi_kategori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinasi',
            name='foto_lainnya',
        ),
        migrations.AddField(
            model_name='destinasi',
            name='foto_lainnya_1',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/secondary/', verbose_name='Foto Gallery 1'),
        ),
        migrations.AddField(
            model_name='destinasi',
            name='foto_lainnya_2',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/secondary/', verbose_name='Foto Gallery 2'),
        ),
        migrations.AddField(
            model_name='destinasi',
            name='foto_lainnya_3',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/secondary/', verbose_name='Foto Gallery 3'),
        ),
        migrations.AddField(
            model_name='destinasi',
            name='foto_lainnya_4',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/secondary/', verbose_name='Foto Gallery 4'),
        ),
        migrations.AlterField(
            model_name='destinasi',
            name='foto_utama',
            field=models.ImageField(upload_to='destinations/primary/', verbose_name='Foto Utama (Hero)'),
        ),
    ]
