# Generated by Django 5.1.3 on 2026-01-18 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_destinasi_foto_lainnya_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinasi',
            options={'verbose_name': 'Destinasi', 'verbose_name_plural': 'Destinasi'},
        ),
        migrations.AlterModelOptions(
            name='kategori',
            options={'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategori'},
        ),
        migrations.AlterField(
            model_name='destinasi',
            name='deskripsi',
            field=models.TextField(verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='destinasi',
            name='jumlah_views',
            field=models.IntegerField(default=0, verbose_name='Jumlah Views'),
        ),
        migrations.AlterField(
            model_name='destinasi',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinasi', to='core.kategori', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='destinasi',
            name='kecamatan',
            field=models.CharField(max_length=100, verbose_name='Kecamatan'),
        ),
        migrations.AlterField(
            model_name='destinasi',
            name='lokasi_maps',
            field=models.CharField(max_length=300, verbose_name='URL Google Maps'),
        ),
        migrations.AlterField(
            model_name='destinasi',
            name='nama_destinasi',
            field=models.CharField(max_length=100, verbose_name='Nama Destinasi'),
        ),
        migrations.AlterField(
            model_name='destinasi',
            name='pengelola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinasi_dikelola', to=settings.AUTH_USER_MODEL, verbose_name='Pengelola'),
        ),
        migrations.AlterField(
            model_name='destinasi',
            name='tanggal_dibuat',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada'),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='nama_kategori',
            field=models.CharField(max_length=100, verbose_name='Nama Kategori'),
        ),
    ]
