# Generated by Django 5.1.3 on 2026-01-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_destinasi_options_alter_kategori_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='deskripsi',
            field=models.TextField(blank=True, null=True, verbose_name='Deskripsi Kategori'),
        ),
    ]
