# Generated by Django 5.1.3 on 2026-01-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_kategori_deskripsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinasi',
            name='kecamatan',
            field=models.CharField(choices=[('Sekotong', 'Sekotong'), ('Lembar', 'Lembar'), ('Gerung', 'Gerung'), ('Labuapi', 'Labuapi'), ('Kediri', 'Kediri'), ('Kuripan', 'Kuripan'), ('Narmada', 'Narmada'), ('Lingsar', 'Lingsar'), ('Gunung Sari', 'Gunung Sari'), ('Batu Layar', 'Batu Layar')], max_length=100, verbose_name='Kecamatan'),
        ),
    ]
