# Generated by Django 5.1.3 on 2026-01-18 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_destinasi_kecamatan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinasi',
            options={'verbose_name': 'Destination', 'verbose_name_plural': 'Destinations'},
        ),
        migrations.AlterModelOptions(
            name='kategori',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='kategori',
            name='icon',
            field=models.CharField(default='category', help_text='Google Material Icon Name (e.g. waves, landscape, restaurant)', max_length=50, verbose_name='Icon Name'),
        ),
        migrations.AlterField(
            model_name='destinasi',
            name='deskripsi',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='destinasi',
            name='foto_lainnya_1',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/secondary/', verbose_name='Gallery Photo 1'),
        ),
        migrations.AlterField(
            model_name='destinasi',
            name='foto_lainnya_2',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/secondary/', verbose_name='Gallery Photo 2'),
        ),
        migrations.AlterField(
            model_name='destinasi',
            name='foto_lainnya_3',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/secondary/', verbose_name='Gallery Photo 3'),
        ),
        migrations.AlterField(
            model_name='destinasi',
            name='foto_lainnya_4',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/secondary/', verbose_name='Gallery Photo 4'),
        ),
        migrations.AlterField(
            model_name='destinasi',
            name='foto_utama',
            field=models.ImageField(upload_to='destinations/primary/', verbose_name='Main Photo (Hero)'),
        ),
        migrations.AlterField(
            model_name='destinasi',
            name='jumlah_views',
            field=models.IntegerField(default=0, verbose_name='Total Views'),
        ),
        migrations.AlterField(
            model_name='destinasi',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinasi', to='core.kategori', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='destinasi',
            name='kecamatan',
            field=models.CharField(choices=[('Sekotong', 'Sekotong'), ('Lembar', 'Lembar'), ('Gerung', 'Gerung'), ('Labuapi', 'Labuapi'), ('Kediri', 'Kediri'), ('Kuripan', 'Kuripan'), ('Narmada', 'Narmada'), ('Lingsar', 'Lingsar'), ('Gunung Sari', 'Gunung Sari'), ('Batu Layar', 'Batu Layar')], max_length=100, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='destinasi',
            name='lokasi_maps',
            field=models.CharField(max_length=300, verbose_name='Google Maps URL'),
        ),
        migrations.AlterField(
            model_name='destinasi',
            name='nama_destinasi',
            field=models.CharField(max_length=100, verbose_name='Destination Name'),
        ),
        migrations.AlterField(
            model_name='destinasi',
            name='pengelola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinasi_dikelola', to=settings.AUTH_USER_MODEL, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='destinasi',
            name='tanggal_dibuat',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='deskripsi',
            field=models.TextField(blank=True, null=True, verbose_name='Category Description'),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='nama_kategori',
            field=models.CharField(max_length=100, verbose_name='Category Name'),
        ),
    ]
