# Generated by Django 5.1.3 on 2026-01-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_destinasi_options_alter_kategori_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinasi',
            name='info_tambahan',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Info'),
        ),
    ]
