# Generated by Django 5.1.3 on 2026-01-22 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_destinasi_info_tambahan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Rename Kategori model FIRST
        migrations.RenameModel(
            old_name='Kategori',
            new_name='Category',
        ),
        # 2. Then rename fields on Category
        migrations.RenameField(
            model_name='category',
            old_name='deskripsi',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='nama_kategori',
            new_name='name',
        ),
        # 3. Rename Destinasi model
        migrations.RenameModel(
            old_name='Destinasi',
            new_name='Destination',
        ),
        # 4. Rename fields on Destination
        migrations.RenameField(
            model_name='destination',
            old_name='nama_destinasi',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='deskripsi',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='kecamatan',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='lokasi_maps',
            new_name='maps_embed_url',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='info_tambahan',
            new_name='additional_info',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='foto_utama',
            new_name='main_image',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='foto_lainnya_1',
            new_name='gallery_image_1',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='foto_lainnya_2',
            new_name='gallery_image_2',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='foto_lainnya_3',
            new_name='gallery_image_3',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='foto_lainnya_4',
            new_name='gallery_image_4',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='pengelola',
            new_name='manager',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='kategori',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='jumlah_views',
            new_name='view_count',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='tanggal_dibuat',
            new_name='created_at',
        ),
        # 5. Update related_name on ForeignKey fields
        migrations.AlterField(
            model_name='destination',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinations', to='core.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_destinations', to=settings.AUTH_USER_MODEL, verbose_name='Manager'),
        ),
        # 6. Add ordering meta option
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['-created_at'], 'verbose_name': 'Destination', 'verbose_name_plural': 'Destinations'},
        ),
    ]
