# Generated by Django 5.1.3 on 2026-01-23 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_refactor_to_english'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='District Name')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='districts/', verbose_name='Thumbnail Image')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='destination',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='gallery_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/secondary/', verbose_name='Gallery 1'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='gallery_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/secondary/', verbose_name='Gallery 2'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='gallery_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/secondary/', verbose_name='Gallery 3'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='gallery_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/secondary/', verbose_name='Gallery 4'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='Legacy View Count'),
        ),
        migrations.CreateModel(
            name='DestinationGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='destinations/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.destination')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
            },
        ),
        migrations.CreateModel(
            name='DestinationView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='core.destination')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'View Log',
                'verbose_name_plural': 'View Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
