# Generated by Django 5.1.3 on 2026-01-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_district_alter_destination_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='district',
        ),
        migrations.AddField(
            model_name='destination',
            name='district_legacy',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='District (Legacy)'),
        ),
    ]
