# Generated by Django 5.1.3 on 2026-01-23 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_destination_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinations', to='core.district', verbose_name='District'),
        ),
    ]
