# Generated by Django 5.1.3 on 2026-01-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_destination_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='Total Views'),
        ),
        migrations.DeleteModel(
            name='DestinationView',
        ),
    ]
