# Generated by Django 5.1.3 on 2026-01-23 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_destination_view_count_delete_destinationview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='district_legacy',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='gallery_image_1',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='gallery_image_2',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='gallery_image_3',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='gallery_image_4',
        ),
    ]
