# Generated by Django 5.1.3 on 2026-01-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_destination_district_legacy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='maps_embed_url',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Google Maps URL'),
        ),
    ]
